#! /usr/bin/env python3

import sys, hashlib, itertools

data = sys.stdin.read().strip()

for number in itertools.count(start=1, step=1):
    message = f"{data}{number}"
    m = hashlib.md5()
    m.update(message.encode("ASCII"))
    digest = m.hexdigest()

    print(message, m.hexdigest(), file=sys.stderr)

    if digest.startswith("000000"):
        print(number)
        break
