#! /usr/bin/env python3

import sys, re

def path_to_root(planet, parents):
    path = []
    current = planet

    while current in parents:
        path.append(current)
        current = parents[current]

    return path

parents = {}
orbits = {}

for line in sys.stdin:
    match = re.match(r"(\w+)\)(\w+).*", line)
    inner = match.group(1)
    outer = match.group(2)

    parents[outer] = inner

you_path = path_to_root("YOU", parents)
san_path = path_to_root("SAN", parents)

print(you_path, file=sys.stderr)
print(san_path, file=sys.stderr)

intersections = set(you_path).intersection(san_path)

print(intersections, file=sys.stderr)

best_dist = float("inf")
for intersection in intersections:
    you_dist = you_path.index(intersection) - 1
    san_dist = san_path.index(intersection) - 1

    print(intersection, you_dist, san_dist, file=sys.stderr)

    overall_dist = you_dist + san_dist

    if overall_dist < best_dist:
        best_dist = overall_dist

print(best_dist)
