#! /usr/bin/env python3

import sys, re

def parse(line):
    matches = re.match(r'(.+) (\d+),(\d+) through (\d+),(\d+)', line)

    x1 = int(matches[2])
    x2 = int(matches[4])
    y1 = int(matches[3])
    y2 = int(matches[5])

    result = {}
    result['type'] = matches[1]
    result['xmin'] = min(x1, x2)
    result['ymin'] = min(y1, y2)
    result['xmax'] = max(x1, x2)
    result['ymax'] = max(y1, y2)

    return result

def update(instr, lights):
    count = 0
    for x in range(instr['xmin'], instr['xmax'] + 1):
        for y in range(instr['ymin'], instr['ymax'] + 1):

            count += 1

            if instr['type'] == 'turn on':
                lights[x][y] = True
            elif instr['type'] == 'turn off':
                lights[x][y] = False
            elif instr['type'] == 'toggle':
                lights[x][y] = not lights[x][y]

def count_ons(lights):
    return sum(sum(l) for l in lights)

lights = [[False] * 1000 for _ in range(1000)]

for line in sys.stdin:
    instruction = parse(line)
    update(instruction, lights)

print(count_ons(lights))
