#! /usr/bin/env python3

import sys

def is_ok(password):
    p = [int(c) for c in str(password)]

    adj = False
    for i in range(len(p) - 1):
        if p[i] == p[i + 1]:
            adj = True

        if p[i] > p[i + 1]:
            print(password, "Decreasing", file=sys.stderr)
            return False

    if adj:
        print(password, "Ok", file=sys.stderr)
        return True
    else:
        print(password, "No adj", file=sys.stderr)
        return False

data = sys.stdin.read()
start = int(data[:6])
end = int(data[7:13])

print(sum(1 for v in range(start, end) if is_ok(v)))
