#! /usr/bin/env python3

import sys, re

def ribbon_needed(dims):
    perimeters = tuple(2*i for i in (dims[0] + dims[1], dims[1] + dims[2], dims[2] + dims[0]))
    volume = dims[0] * dims[1] * dims[2]

    return min(perimeters) + volume

def parse_dims(line):
    matches = re.match(r"(\d+)x(\d+)x(\d+)", line)
    return (int(matches[1]), int(matches[2]), int(matches[3]))

print(sum(ribbon_needed(parse_dims(line)) for line in sys.stdin))
