#! /usr/bin/env python3

import sys

def intcode_step(program, pc):
    opcode = program[pc]
    in1_pos = program[pc + 1]
    in2_pos = program[pc + 2]
    out_pos = program[pc + 3]

    if opcode == 1:
        program[out_pos] = program[in1_pos] + program[in2_pos]
    elif opcode == 2:
        program[out_pos] = program[in1_pos] * program[in2_pos]
    elif opcode == 99:
        print(program[0])
        sys.exit()
    else:
        print(f"Error: Invalid opcode {opcode} at position {pc}")
        sys.exit()

data = list(int(item) for item in sys.stdin.read().split(","))

# One-off changes in the problem text
data[1] = 12
data[2] = 2

pc = 0
while True:
    intcode_step(data, pc)
    pc += 4
