#! /usr/bin/env python3

import sys
import json

def add_up(data):
    if isinstance(data, list):
        return sum(add_up(v) for v in data)
    elif isinstance(data, dict):
        if "red" in data.values():
            return 0
        else:
            return sum(add_up(v) for v in data.values())
    elif isinstance(data, int):
        return data
    elif isinstance(data, str):
        return 0
    else:
        raise Exception("Not sure how to deal with " + repr(type(data)))

data = json.load(sys.stdin)

print(add_up(data))
